# LibreLane configuration file

DESIGN_NAME: heichips25_template
VERILOG_FILES: ["dir::../src/heichips25_template.sv", "dir::../src/top.sv","dir::../src/toptop.sv", "dir::../src/Demo_Data_full.sv", "dir::../src/bpsk_demod.sv", "dir::../src/psk8_demodulator.sv", "dir::../src/qam16_demodulator.sv", "dir::../src/qpsk_demod.sv","dir::../src/demux_1to4.sv", "dir::../src/All_mod.sv", "dir::../src/bpsk_mapper.sv", "dir::../src/psk8_mapper.sv", "dir::../src/qam16_mapper.sv", "dir::../src/qpsk_mapper.sv"]
CLOCK_PORT: clk
CLOCK_PERIOD: 10 # 10ns = 100MHz



# Reduce wasted space
TOP_MARGIN_MULT: 1
BOTTOM_MARGIN_MULT: 1
LEFT_MARGIN_MULT: 6
RIGHT_MARGIN_MULT: 6

# Absolute die size
FP_SIZING: absolute

# Small DEF template
DIE_AREA: [0, 0, 500, 200]
FP_DEF_TEMPLATE: dir::def/heichips25_template_small.def

# Large DEF template
#DIE_AREA: [0, 0, 500, 415]
#FP_DEF_TEMPLATE: dir::def/heichips25_template_large.def

# Don't use power rings or TopMetal2 layer
PDN_MULTILAYER: false
RT_MAX_LAYER: TopMetal1

# Enable for better SystemVerilog support
#USE_SLANG: true